---
  - name: installer postgres et ses dependences
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - postgresql-server
        - postgresql
        - postgresql-libs
        - python-psycopg2
        - postgresql-contrib


  - name: Verifier si postgre est initialisé
    stat:
      path: "/var/lib/pgsql/data/PG_VERSION"
    register: pgdata_dir_version

  - name: Initialiser postgre s'il n'est pas initialisé
    command: postgresql-setup initdb
    when: not pgdata_dir_version.stat.exists

  - name: demarrer postgresql s'il n'est pas demarré
    service:
      name: postgresql
      state: started

  - name: Creation de la base de donnée
    become_user: postgres
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    become_user: postgres
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: ensure user does not have unnecessary privilege
    become_user: postgres
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB

  - name: ensure no other user can access the database
    become_user: postgres
    postgresql_privs: db={{dbname}} role=PUBLIC type=database priv=ALL state=absent

  - name: replace line
    lineinfile:
      dest: /var/lib/pgsql/data/postgresql.conf
      regexp: "^(.*)#listen_addresses =(.*)$"
      line: "listen_addresses ='*'"
      state: present
      backrefs: yes

  - name: authoriser l'acces pour mattermost
    lineinfile:
      path: /var/lib/pgsql/data/pg_hba.conf
      line: "host all all {{item}}/32 md5"
      create: yes
    with_items:
      - "{{mattermostip}}"


  - name: redeamarrer postgresql
    service:
      name: postgresql
      state: restarted